
services:

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  queue-service:
    build:
      context: ./queue-service
      dockerfile: Dockerfile
    environment:
      - START_PORT=50051
      - PORT_RANGE=50
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    entrypoint: ["/app/entrypoint.sh"]
    restart: unless-stopped
    depends_on:
      - redis
    deploy:
      replicas: 5

  test-runner:
    build:
      context: ./queue-service
      dockerfile: Dockerfile
    entrypoint: ["/app/test-runner.sh"]
    volumes:
      - ./tests:/app/tests
      - ./queue-service/test-runner.sh:/app/test-runner.sh
      - ./test_runner.py:/app/test_runner.py
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - START_PORT=50051
      - PORT_RANGE=50
      - PYTHONPATH=/app
    depends_on:
      - queue-service
      - redis
    restart: "no"
